[package]
name = "nhl-linescores"
version = "0.1.0"
authors = ["Sara Federico <sfed617@gmail.com>"]

[dependencies]
chrono = { version = "*", features = ["serde"] }
colored = "1.6"
curl = "*"
plotlib = "*"
serde_json = "1.0"
serde_derive = "*"
serde = "*"
time = "*"
